import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { ToTop } from '../components/ToTop';
import { useState } from 'react';
import { Auth } from './auth';
import Home from './home';
import { AboutUs } from './about';
import { Contact } from './contact';

const Main: NextPage = () => {
  const Map = dynamic(() => import('../components/Map.jsx') as any, { ssr: false });
  const [language, setLanguage] = useState('EN');
  const [page, setPage] = useState('collectibles');

  const handleLanguageToggle = () => {
    setLanguage((prevLanguage) => (prevLanguage === 'TH' ? 'EN' : 'TH'));
    console.log('handleLanguageToggle', language);
  };

  const handlePageChange = (newPage: string) => {
    console.log('Page change requested:', newPage);
    setPage(newPage);
  };

  return (
    <div>
      <Head>
        <title>Top Pa</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800&family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Navbar
          language={language}
          onLanguageToggle={handleLanguageToggle}
          onPageChange={handlePageChange}
        />
      </div>
      {page === 'collectibles' && <Home language={language} />}
      {page === 'signin' && <Auth language={language} />}
      {page === 'about' && <AboutUs language={language} />}
      {page === 'contact' && <Contact language={language} />}
      <div className="mt-40 relative">
        <ToTop />
      </div>
      <Footer language={language} onPageChange={handlePageChange} />
    </div>
  );
};

export default Main;