import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import { CardItem } from '../components/CardItem';
import { Landing } from '../components/Landing';
import { Navbar } from '../components/Navbar';
import { BigCard } from '../components/BigCard';
import img1 from '../public/imgs/cardImg1.svg';
import img2 from '../public/imgs/cardImg2.svg';
import img3 from '../public/imgs/cardImg3.svg';
import river from '../public/imgs/river.svg';
import mountains from '../public/imgs/mountains.svg';
import beach from '../public/imgs/beach.svg';
import booking from '../public/imgs/booking.svg';
import EmojiEmotionsIcon from '@mui/icons-material/EmojiEmotions';
import SelfImprovementIcon from '@mui/icons-material/SelfImprovement';
import LandscapeIcon from '@mui/icons-material/Landscape';
import { AccordionCard } from '../components/AccordionCard';
import { Footer } from '../components/Footer';
import { ToTop } from '../components/ToTop';
import { useInView } from 'react-intersection-observer';
import { Alert, AlertTitle } from '@mui/material';
import { useState } from 'react';
import usePassportData from '../hooks/usePassportData';
import { Auth } from './auth';
import Home from './home';
import { AboutUs } from './about'; // Import the AboutUs component
import { Contact } from './contact'; // Import the Contact component

const Main: NextPage = () => {
  const Map = dynamic(() => import('../components/Map.jsx') as any, { ssr: false });
  const [language, setLanguage] = useState('EN'); // Language state in Main
  const [page, setPage] = useState('collectibles'); // Page state in Main

  const handleLanguageToggle = () => {
    setLanguage((prevLanguage) => (prevLanguage === 'TH' ? 'EN' : 'TH'));
    console.log('handleLanguageToggle', language);
  };

  const handlePageChange = (page: string) => {
    console.log('Page change requested:', page);
    setPage(page);
  };

  return (
    <div>
      <Head>
        <title>Top Pa</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800&family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Navbar
          language={language}
          onLanguageToggle={handleLanguageToggle}
          onPageChange={handlePageChange}
        />{' '}
        {/* Pass state and handler */}
      </div>
      {page === 'collectibles' && <Home />}
      {page === 'signin' && <Auth  language={language}/>}
      {page === 'about' && <AboutUs language={language}/>} {/* Render AboutUs component */}
      {page === 'contact' && <Contact language={language}/>} {/* Render Contact component */}
      <div className="mt-40 relative">
        <ToTop />
      </div>
      <Footer language={language} onPageChange={handlePageChange}/>
    </div>
  );
};

export default Main;